### PR TITLE
WIP Update PlayBot.java

### PR DESCRIPTION
**Pull request by ppolakiewicz**

### CODE REVIEW

**Review by devdo-eu — CHANGES_REQUESTED** [review]
WTF?
`Move.SCAN` repeated two times inside enum/dictionary?

**Comment by devdo-eu** [comment]
ok - I got it. 
But you can write WIP at PR title - then i will know that it is test/work in progress pull request

**Comment by ppolakiewicz** [comment]
Yeah, my bad I should

**Comment by ppolakiewicz** [comment]
Anyway this second action for java bot didn't start

**Pull request closed without merging**
